### ISSUE TITLE
Incorrectly labeled dates in calibration_single.py?

### ISSUE THREAD

**Issue by ypwong22** [CWatM/CWatM#1]
Dear developers, we are applying CWatM to a basin in the United States. It seems that Ln 491 of "calibration_single.py" has a minor glitch. The "streamflow_simulated_best.csv" file that we get is labeled from the ForcingStart instead of ForcingStart + Spin-up dates. 

Yaoping

**Comment by ypwong22** [comment]
Hi Peter, 

Thank you. So, even if I set ForcingStart = the SpinUp date, the model will perform the spinup during calibration?

Yaoping

**Comment by CWatM** [comment]
Hi Yaoping,

yes the model will perform the spin up. 
The calibration module is only triggering the CWATM model each time with different calibration parameters. The model itself performs what is wrtiten in the settings.ini for the model (in the template folder) and if you put a spin up there it will be performed.

**Comment by ypwong22** [comment]
Thank you. I see.

Yaoping
